# Generated by Django 6.0.3 on 2026-03-12 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafioBackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desafioBackend.aluno')),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desafioBackend.curso')),
            ],
        ),
    ]
