# Generated by Django 6.0.3 on 2026-03-29 20:01

import desafioBackend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafioBackend', '0002_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='status',
            field=models.CharField(choices=[('ativa', 'Ativa'), ('cancelada', 'Cancelada'), ('concluida', 'Concluida')], default='ativa', max_length=20),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='email',
            field=models.EmailField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(max_length=100, validators=[desafioBackend.models.valida_nome]),
        ),
    ]
